import Head from "next/head";
import Layout from "@/Components/Layout";
import Image from "next/image";
import rehmanoon from "../../public/images/profile/rehmanoon.png";
import AnimatedText from "@/Components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/Components/Icons";
import HireMe from "@/Components/HireMe";
import Transition from "@/Components/Transition";

export default function Home() {
  return (
    <>
      <Head>
        <title> Abdul Rehman Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light ">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={rehmanoon}
                alt="rehman"
                className="w-full h-auto lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>

            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center ">
              <AnimatedText
                text="Transforming Ideas Into  Reality Through Code and Design."
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a passionate front-end developer, I thrive on transforming
                creative ideas into visually stunning and interactive websites.
                I dont just code I craft immersive online experiences that
                captivate and inspire. Lets bring your vision to life and make
                the web a cooler place together!
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/CV Abdul Rehman.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg
              font-semibold hover:bg-light hover:text-dark border-2  border-solid border-transparent
              hover : border-dark dark:bg-light dark:text-dark hover:dark:bg-dark
              hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base "
                  // download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:rehmanbanday5@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light
                  md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
